version: '2'

services:
  node:
    build: ./docker/node
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "8086:9999"
      - "35729:35729"
    environment:
      - NODE_ENV=development
      - PG_CONNECTION_STRING=postgres://meetings:meetings@db:5432
    command: grunt
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - meetingspgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: meetings
      POSTGRES_USER: meetings
      POSTGRES_PASSWORD: meetings


volumes:
  meetingspgdata:
